### ISSUE TITLE
App fails to run: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

### ISSUE THREAD

**Issue by rhymeswithmogul** [whatihavedone/lrc_fetcher#5]
This might be an issue with my system, but when I try to run `scrapy runspider lyrics_fetcher.py`, the script fails to run, throwing an AttributeError related to OpenSSL.

```
Traceback (most recent call last):
  File "/home/colin/.local/bin/scrapy", line 5, in <module>
    from scrapy.cmdline import execute
  File "/home/colin/.local/lib/python3.10/site-packages/scrapy/__init__.py", line 15, in <module>
    from scrapy.spiders import Spider
  File "/home/colin/.local/lib/python3.10/site-packages/scrapy/spiders/__init__.py", line 99, in <module>
    from scrapy.spiders.crawl import CrawlSpider, Rule
  File "/home/colin/.local/lib/python3.10/site-packages/scrapy/spiders/crawl.py", line 15, in <module>
    from scrapy.utils.spider import iterate_spider_output
  File "/home/colin/.local/lib/python3.10/site-packages/scrapy/utils/spider.py", line 5, in <module>
    from scrapy.utils.defer import deferred_from_coro
  File "/home/colin/.local/lib/python3.10/site-packages/scrapy/utils/defer.py", line 33, in <module>
    from scrapy.utils.reactor import _get_asyncio_event_loop, is_asyncio_reactor_installed
  File "/home/colin/.local/lib/python3.10/site-packages/scrapy/utils/reactor.py", line 8, in <module>
    from twisted.internet import asyncioreactor, error
  File "/usr/lib/python3/dist-packages/twisted/internet/asyncioreactor.py", line 19, in <module>
    from twisted.internet.posixbase import (
  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 19, in <module>
    from twisted.internet import error, tcp, udp
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 37, in <module>
    from twisted.internet._newtls import (
  File "/usr/lib/python3/dist-packages/twisted/internet/_newtls.py", line 18, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/lib/python3/dist-packages/twisted/protocols/tls.py", line 40, in <module>
    from OpenSSL.SSL import (
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

`openssl version` says: "OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)"

Apologies if this winds up not being an app issue, but a problem with my computer.

**Comment by rhymeswithmogul** [comment]
Never mind, [I had to upgrade some modules](https://stackoverflow.com/questions/74981558/error-updating-python3-pip-attributeerror-module-lib-has-no-attribute-openss).

```bash
python3 -m pip install -U pyopenssl cryptography
```
